# Generated by Django 2.2 on 2019-05-19 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Equipamiento de la habitación',
                'verbose_name_plural': 'Equipamientos de las habitaciones',
            },
        ),
        migrations.CreateModel(
            name='RoomStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Estado de la habitación',
                'verbose_name_plural': 'Estados de las habitaciones',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('capacity', models.SmallIntegerField(verbose_name='Capacidad (personas)')),
            ],
            options={
                'verbose_name': 'Tipo de habitación',
                'verbose_name_plural': 'Tipos de habitaciones',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(unique=True, verbose_name='Número de habitación')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio')),
                ('facilities', models.ManyToManyField(related_name='room_facilities', to='core.RoomFacility', verbose_name='Equipamiento')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_status', to='core.RoomStatus', verbose_name='Estado de la habitación')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_type', to='core.RoomType', verbose_name='Tipo de habitación')),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
            },
        ),
    ]
