# Generated by Django 2.2 on 2019-05-19 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, verbose_name='Localizador')),
                ('check_in', models.DateField(verbose_name='Fecha ingreso')),
                ('check_out', models.DateField(verbose_name='Fecha salida')),
                ('card_number', models.CharField(max_length=19, verbose_name='Número de tarjeta')),
                ('expiry_month', models.CharField(max_length=2, verbose_name='Mes expiración')),
                ('expiry_year', models.CharField(max_length=2, verbose_name='Año expiración')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total reserva')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha reserva')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Huésped')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_reservation', to='core.Room', verbose_name='Habitación')),
            ],
            options={
                'verbose_name': 'Reserva',
            },
        ),
    ]
